# dungeon/localization.py

import os
from . import config

# UI 및 시스템 메시지 번역 맵
TRANSLATIONS = {
    "ko": {
        # UI Elements
        "Level": "레벨", "Exp": "경험치", "Job": "직업", "Gold": "골드", "Floor": "층",
        "HP": "HP", "MP": "MP", "Stamina": "스테미너", "Inventory": "인벤토리",
        "Shop": "상점", "Main Menu": "메인 메뉴", "Name": "이름", "Experience": "경험치",
        "Stat Points": "스탯 포인트", "Select your class:": "당신의 직업을 선택하세요:",
        "Detail Stats": "상세 능력치", "Basic Skill": "기본 스킬", "Log": "로그",
        "ATT": "공격", "DEF": "방어", "RNG": "사거리",
        "Move": "이동", "Wait": "대기", "Quickslot": "퀵슬롯", "Close": "닫기",
        "Enter your name": "당신의 이름은 무엇입니까?", "(Max 10 chars)": "(최대 10자)",
        "Equipment": "장비", "Items": "아이템", "No items": "아이템 없음",
        "No equipped items": "장착된 아이템 없음", "Confirm": "확인", "Yes": "예", "No": "아니오",
        "Back": "뒤로 가기", "Load": "불러오기", "Delete": "삭제",
        "No saved games.": "저장된 게임이 없습니다.",
        "Select skill to recharge": "충전할 스킬 선택",
        "Select equipment to repair": "수리할 장비 선택",
        "Select item to identify": "감정할 아이템 선택",
        "No skills available": "사용 가능한 스킬이 없습니다!",
        "No items to repair": "수리할 아이템이 없습니다!",
        "No items to identify": "감정할 아이템이 없습니다!",
        "New Game": "새 게임", "Continue": "이어하기", "Exit Game": "게임 종료",
        "Select": "선택", "GAME OVER": "게임 종료",
        "Press any key to return to Main Menu.": "아무 키나 눌러 메인 메뉴로 돌아갑니다.",
        "Damage": "데미지", "Defense": "방어력",
        "Attack": "공격력", "AC": "방어력(AC)",
        "Equipment/Req": "공격력/장비착용", "Max MP": "최대 마력(MP)", "AC/Hit": "방어력(AC)/명중", "Max HP": "최대 체력(HP)",
        "Dungeon Map": "던전 맵", "Player Condition": "플레이어 상태",
        "STR (Str)": "STR (힘)", "MAG (Mag)": "MAG (마력)", "DEX (Dex)": "DEX (민첩)", "VIT (Vit)": "VIT (활력)",
        "Hall of Fame": "명예의 전당", "Hall of Dishonor": "불명예의 전당",
        "Legendary {} {}": "전설의 {} {}", "Forgotten {} {}": "잊혀진 {} {}",
        "Defeated Diablo and saved the world": "디아블로를 물리치고 세상을 구원함",
        "Final Location: Floor {}": "최후의 장소: {}층", "Cause of Death: {}": "사망 원인: {}",
        "Total Turns: {}": "총 전투 턴 수: {}", "Date: {}": "날짜: {}", "No Records": "기록 없음",
        "[1st]": "[1위]", "[2nd]": "[2위]", "[3rd]": "[3위]",
        
        # Combat Messages
        "Attack!": "공격!", "Defend!": "방어!", "Miss!": "빗나감!", "Critical!": "크리티컬!",
        "You died...": "사망했습니다...", "Victory!": "승리!",
        
        # System Messages
        "Save complete.": "저장이 완료되었습니다.", "Load complete.": "로드가 완료되었습니다.",

        # New Additions
        "LOGS": "로그", "EQUIP": "장비", "QUICK SLOTS": "퀵슬롯", "SKILLS": "스킬", "ACTIVE EFFECTS": "진행 효과",
        "Head": "머리", "Body": "몸통", "Hand1": "손1", "Hand2": "손2", "Gloves": "장갑", "Boots": "신발", "Neck": "목", "Ring1": "반지1", "Ring2": "반지2",
        "recovered": "회복되었습니다.",
        
        # Game Start Messages
        "WASD나 방향키로 이동하고 몬스터와 부딪혀 전투하세요.": "WASD나 방향키로 이동하고 몬스터와 부딪혀 전투하세요.",
        
        # Inventory UI
        "선택:": "선택:",
        "이름:": "이름:",
        "설명:": "설명:",
        "필요 레벨:": "필요 레벨:",
        "공격:": "공격:",
        "방어:": "방어:",
        "사거리:": "사거리:",
        "효과:": "효과:",
        
        # Character Sheet
        "STR (힘)": "STR (힘)",
        "MAG (마력)": "MAG (마력)",
        "DEX (민첩)": "DEX (민첩)",
        "VIT (활력)": "VIT (활력)",
        "Points:": "포인트:",
        
        # Shop UI
        "사기 (BUY)": "사기 (BUY)",
        "팔기 (SELL)": "팔기 (SELL)",
        "소지 골드:": "소지 골드:",
        "구매": "구매",
        "판매": "판매",
        "[←/→] 탭 전환  [↑/↓] 선택  [ENTER]": "[←/→] 탭 전환  [↑/↓] 선택  [ENTER]",
        " [B] 뒤로/닫기": " [B] 뒤로/닫기",
        
        # Shrine UI
        "강화할 장비 선택": "강화할 장비 선택",
        "[ENTER] 강화  [ESC] 취소": "[ENTER] 강화  [ESC] 취소",
        
        # Inventory Tabs
        "아이템": "아이템",
        "장비": "장비",
        "스크롤": "스크롤",
        "스킬": "스킬",
        
        # Stat Descriptions
        "공격력 / 무기효율": "공격력 / 무기효율",
        "최대마력 / 마법효율": "최대마력 / 마법효율",
        "방어력 / 명중률 / 치명타": "방어력 / 명중률 / 치명타",
        "최대체력 / 생존력": "최대체력 / 생존력",
        
        # Control Guides
        "[↑/↓] 선택  [→/ENTER] 포인트 투자  [C/ESC] 닫기": "[↑/↓] 선택  [→/ENTER] 포인트 투자  [C/ESC] 닫기",
        "[←/→] 탭  [↑/↓] 선택  [ENTER/E] 등록/해제  [X] 스킬 잊기  [B] 닫기": "[←/→] 탭  [↑/↓] 선택  [ENTER/E] 등록/해제  [X] 스킬 잊기  [B] 닫기",
        "[←/→] 탭  [↑/↓] 선택  [E] 퀵슬롯 등록  [ENTER] 사용/장착  [B] 닫기": "[←/→] 탭  [↑/↓] 선택  [E] 퀵슬롯 등록  [ENTER] 사용/장착  [B] 닫기",
        
        # Dungeon Messages
        "던전 {}층 [{}]에 입장했습니다.": "던전 {}층 [{}]에 입장했습니다.",
        "[경고] 강력한 보스의 기운이 느껴집니다!": "[경고] 강력한 보스의 기운이 느껴집니다!",
        "[경고] {}이(가) 나타났습니다!": "[경고] {}이(가) 나타났습니다!",
        "강력한 적": "강력한 적",
        "{}의 환영": "{}의 환영",
        
        # Entity Types
        "상인": "상인",
        "신전": "신전",
        
        # Item Names (for shop defaults)
        "체력 물약": "체력 물약",
        "마력 물약": "마력 물약",
        "확인 스크롤": "확인 스크롤",
        
        # Additional Shop & Engine Messages
        "상점에 오신 것을 환영합니다!": "Welcome to the shop!",
        "저장하고 메인 메뉴로 돌아갑니다...": "Saving and returning to main menu...",
        "몸이 움직이지 않아 아이템을 조작할 수 없습니다!": "You cannot manipulate items while immobilized!",
        "{}을(를) 인벤토리에서 찾을 수 없습니다.": "Could not find {} in inventory.",
        "{} 스킬 데이터가 없습니다.": "No skill data for {}.",
        "{}번 스킬 슬롯이 비어있습니다.": "Skill slot {} is empty.",
        "아이템 퀵슬롯": "Item Quickslot",
        "스킬 퀵슬롯": "Skill Quickslot",
        "방향을 선택하세요...": "Select a direction...",
        "상성 우위! +{}%": "Advantage! +{}%",
        "상성 열위.. -{}%": "Disadvantage.. -{}%",
        
        # Shrine & Enhancement Messages
        "신전의 축복을 선택하세요:": "Choose the Shrine's blessing:",
        "[↑/↓] 선택  [ENTER] 확인  [Q] 나가기": "[↑/↓] Select  [ENTER] Confirm  [Q] Exit",
        "강화할 장비를 선택하세요:": "Select equipment to enhance:",
        "[↑/↓] 선택  [ENTER] 다음  [B] 뒤로  [Q] 닫기": "[↑/↓] Select  [ENTER] Next  [B] Back  [Q] Close",
        "사용할 오일을 선택하세요:": "Select oil to use:",
        "[←/→] 선택  [ENTER] 확인  [B] 뒤로  [Q] 닫기": "[←/→] Select  [ENTER] Confirm  [B] Back  [Q] Close",
        "봉납할 제물을 선택하세요:": "Select an offering to sacrifice:",
        "[↑/↓] 선택  [ENTER] 강화 실행  [B] 뒤로  [Q] 닫기": "[↑/↓] Select  [ENTER] Enhance  [B] Back  [Q] Close",
        "이미 최대 강화 등급입니다!": "Already at maximum enhancement level!",
        "강화 성공! {}": "Enhancement Success! {}",
        "강화 실패... {}의 내구도가 감소했습니다.": "Enhancement Failed... {} durability decreased.",
        "강화 실패! {}이(가) 파손되었습니다!": "Enhancement Failed! {} was damaged!",
        "강화 실패! {}이(가) 산산조각 났습니다...": "Enhancement Failed! {} was shattered...",
        "{}의 전리품: {}이(가) 떨어졌습니다!": "{}'s Loot: {} dropped!",
        "{}의 효과로 능력이 향상되었습니다!": "Attributes increased by effect of {}!",
        "'{}' 발동! (Lv.{}, {})": "'{}' Activated! (Lv.{}, {})",
        "마법 장막이 생겨나 데미지를 마나로 흡수합니다! (지속 {}초)": "A magic veil appears, absorbing damage into mana! (Duration {}s)",
        "차원 문을 통해 이동했습니다! ({}, {})": "Moved through a dimensional gate! ({}, {})",
        "!!! '{}' 폭발 !!!": "!!! '{}' Explosion !!!",
        "[{}]의 내구도를 {} 회복했습니다.": "Recovered {} durability for [{}].",
        "함정 {}개를 안전하게 해제했습니다! (+{}XP){}(성공률 {}%)": "Safely disarmed {} traps! (+{}XP){}(Success rate {}%)",
        "해제에 실패하여 함정 {}개가 발동되었습니다! (피해 감쇄 {}%)": "Failed to disarm, {} traps triggered! (Damage reduction {}%)",
        "주변에 해제할 함정이 발견되지 않았습니다.": "No traps found nearby to disarm.",
        "지팡이에 마력을 {}회 충전했습니다! ({}/{})": "Charged staff with {} mana! ({}/{})",
        "지팡이의 마력이 이미 가득 차 있습니다.": "Staff's mana is already full.",
        "마력을 충전할 지팡이를 들고 있지 않습니다.": "마력을 충전할 지팡이를 들고 있지 않습니다.",
        "시공간이 뒤틀리며 무작위 위치로 이동했습니다! ({}, {})": "시공간이 뒤틀리며 무작위 위치로 이동했습니다! ({}, {})",
        "이동할 수 있는 빈 공간이 없습니다.": "이동할 수 있는 빈 공간이 없습니다.",
        "체력을 {} 회복했습니다!": "체력을 {} 회복했습니다!",
        "'{}'가 분노를 폭발시킵니다! (지속 {}초)": "'{}'가 분노를 폭발시킵니다! (지속 {}초)",
        "'{}'!! 번개 폭발이 주변을 뒤덮습니다!": "'{}'!! 번개 폭발이 주변을 뒤덮습니다!",
        "'{}'!!! 종말의 불꽃이 모든 것을 뒤덮습니다!": "'{}'!!! 종말의 불꽃이 모든 것을 뒤덮습니다!",
        "'{}'!! 수호자 포탑을 소환합니다!": "'{}'!! 수호자 포탑을 소환합니다!",
        "'{}'!! 강력한 진흙 골렘을 소환합니다!": "'{}'!! 강력한 진흙 골렘을 소환합니다!",
        "'{}'!! 서늘한 번개 파동이 퍼져나갑니다!": "'{}'!! 서늘한 번개 파동이 퍼져나갑니다!",
        "상인을 만났습니다. (거래 가능)": "상인을 만났습니다. (거래 가능)",
        "{}와 충돌했습니다. 전투가 시작됩니다.": "{}와 충돌했습니다. 전투가 시작됩니다.",
        "알 수 없는 엔티티와 충돌했습니다.": "알 수 없는 엔티티와 충돌했습니다.",
        "충돌 발생: {}": "충돌 발생: {}",
        "사용할 오일을 선택하세요:": "사용할 오일을 선택하세요:",
        "(사용 가능한 오일이 없습니다)": "(사용 가능한 오일이 없습니다)",
        "특별한 제물을 바치시겠습니까?": "특별한 제물을 바치시겠습니까?",
        "제물을 바치면 강화 성공률이 오르거나": "제물을 바치면 강화 성공률이 오르거나",
        "아이템 파괴를 방지할 수 있습니다.": "아이템 파괴를 방지할 수 있습니다.",
        "봉납할 제물을 선택하세요:": "봉납할 제물을 선택하세요:",
        "(보유 중인 제물이 없습니다. 그대로 강화하시겠습니까?)": "(보유 중인 제물이 없습니다. 그대로 강화하시겠습니까?)",
        "[ENTER]를 누르면 제물 없이 강화를 시작합니다.": "[ENTER]를 누르면 제물 없이 강화를 시작합니다.",
        " [↑/↓] 선택  [ENTER] 감정  [ESC] 취소 ({}/{}) ": " [↑/↓] 선택  [ENTER] 감정  [ESC] 취소 ({}/{}) ",
        "Dungeon Map": "던전 맵",
        "Player Condition": "플레이어 상태",
        "Log": "로그",
        "Gold": "골드",
        "Close": "닫기",
        "이름": "이름",
        "경험치": "경험치",
        "스탯 포인트": "스탯 포인트",
        "공격력": "공격력",
        "방어력": "방어력",
        "Equipment/Req": "공격력/장비착용",
        "Max MP": "최대 마력(MP)",
        "AC/Hit": "방어력(AC)/명중",
        "Max HP": "최대 체력(HP)",

        # System & Combat Messages
        "{}가 분노에 이끌려 달려옵니다!": "{} rushes forward in a rage!",
        "{}가 갑자기 이동했습니다!": "{} moved suddenly!",
        "도살자: \"Ah... Fresh Meat!\"": "Butcher: \"Ah... Fresh Meat!\"",
        "{}가 '{}'을(를) 모방하여 시전합니다!": "{} mimics and casts '{}'!",
        "도살자가 분노하여 지원군을 부릅니다!": "The Butcher calls for reinforcements in fury!",
        "해골 왕이 영원한 충성을 요구합니다!": "The Skeleton King demands eternal loyalty!",
        "{}가 지원군을 부릅니다!": "{} calls for reinforcements!",
        "해골 왕이 죽은 자를 다시 일으켜 세웁니다!": "The Skeleton King raises the dead!",
        "디아블로가 파멸의 화염(Apocalypse)을 시전합니다!": "Diablo casts Apocalypse!",
        "화염이 {}을 덮쳐 {}의 피해를 입혔습니다!": "The flames engulfed {} for {} damage!",
        "'{}'의 원거리 공격!": "Ranged attack of '{}'!",
        "공격이 벽에 막혔습니다.": "Attack blocked by wall.",
        "{source}에서 {}을(를) 획득했습니다!": "Obtained {} from {source}!",
        "{source}를 살펴봅니다... 아무것도 발견하지 못했습니다.": "Examines {source}... Found nothing.",
        "도살자의 식칼에 베여 과다출혈이 발생합니다!": "The Butcher's cleaver causes excessive bleeding!",
        "{}이(가) 출혈 상태가 되었습니다!": "{} is now bleeding!",
        "마법 장막이 {}의 피해를 흡수했습니다! (남은 MP: {})": "Mana Shield absorbed {} damage! (Remaining MP: {})",
        "'{}'이(가) 강력한 충격으로 경직되었습니다!": "'{}' is stunned by a powerful impact!",
        "[경고] {}의 {}이(가) 파손되었습니다!": "[Warning] {}'s {} was damaged!",
        "{}이(가) 충격으로 기절했습니다!": "{} is stunned by the impact!",
        "주변의 적들이 공격에 휘말립니다!": "Nearby enemies are caught in the attack!",
        "{}이(가) 공격을 받아 잠에서 깨어났습니다!": "{} woke up from the attack!",
        "{}이(가) 쓰러졌습니다!": "{} has fallen!",
        "경험치 {}를 획득했습니다.": "Gained {} experience.",
        "{}이(가) 강력한 포효와 함께 지원군을 부릅니다!": "{} calls for reinforcements with a mighty roar!",
        "기술이 준비되지 않았습니다! ({}초)": "Skill is not ready! ({}s)",
        "지팡이에 '{}' 마력을 충전했습니다!": "Charged staff with '{}' power!",
        "충전을 취소했습니다.": "Recharge canceled.",
        "수리할 장비가 없습니다.": "No equipment to repair.",
        "수리가 필요한 아이템이 없습니다.": "No items need repair.",
        "'{}' 수리에 성공했습니다!": "Successfully repaired '{}'!",
        "'{}' 수리에 실패했습니다...": "Failed to repair '{}'...",
        "수리를 취소했습니다.": "Repair canceled.",
        "알 수 없는 스킬입니다: {}": "Unknown skill: {}",
        "보물상자?": "Treasure Chest?",
        "승리": "Victory",
    },
    "en": {
        "Level": "Level", "Exp": "Exp", "Job": "Job", "Gold": "Gold", "Floor": "Floor",
        "HP": "HP", "MP": "MP", "Stamina": "Stamina", "Inventory": "Inventory",
        "Shop": "Shop", "Main Menu": "Main Menu", "Name": "Name", "Experience": "Experience",
        "Stat Points": "Stat Points", "Select your class:": "Select your class:",
        "Detail Stats": "Detail Stats", "Basic Skill": "Basic Skill", "Log": "Log",
        "ATT": "ATK", "DEF": "DEF", "RNG": "RNG",
        "Move": "Move", "Wait": "Wait", "Quickslot": "Quickslot", "Close": "Close",
        "Enter your name": "What is your name?", "(Max 10 chars)": "(Max 10 chars)",
        "Equipment": "Equipment", "Items": "Items", "No items": "No items",
        "No equipped items": "No equipped items", "Confirm": "Confirm", "Yes": "Yes", "No": "No",
        "Back": "Back", "Load": "Load", "Delete": "Delete",
        "No saved games.": "No saved games.",
        "Select skill to recharge": "Select skill to recharge",
        "Select equipment to repair": "Select equipment to repair",
        "Select item to identify": "Select item to identify",
        "No skills available": "No skills available!",
        "No items to repair": "No items to repair!",
        "No items to identify": "No items to identify!",
        "New Game": "New Game", "Continue": "Continue", "Exit Game": "Exit Game",
        "Select": "Select", "GAME OVER": "GAME OVER",
        "Press any key to return to Main Menu.": "Press any key to return to Main Menu.",
        "Damage": "Damage", "Defense": "Defense",
        "Attack": "Attack", "AC": "AC",
        "Equipment/Req": "Equipment/Req", "Max MP": "Max MP", "AC/Hit": "AC/Hit", "Max HP": "Max HP",
        "Dungeon Map": "Dungeon Map", "Player Condition": "Player Condition",
        "STR (Str)": "STR (Str)", "MAG (Mag)": "MAG (Mag)", "DEX (Dex)": "DEX (Dex)", "VIT (Vit)": "VIT (Vit)",
        "Hall of Fame": "Hall of Fame", "Hall of Dishonor": "Hall of Dishonor",
        "Legendary {} {}": "Legendary {} {}", "Forgotten {} {}": "Forgotten {} {}",
        "Defeated Diablo and saved the world": "Defeated Diablo and saved the world",
        "Final Location: Floor {}": "Final Location: Floor {}", "Cause of Death: {}": "Cause of Death: {}",
        "Total Turns: {}": "Total Turns: {}", "Date: {}": "Date: {}", "No Records": "No Records",
        "[1st]": "[1st]", "[2nd]": "[2nd]", "[3rd]": "[3rd]",
        
        "Attack!": "Attack!", "Defend!": "Defend!", "Miss!": "Miss!", "Critical!": "Critical!",
        "You died...": "You died...", "Victory!": "Victory!",
        
        "Save complete.": "Save complete.", "Load complete.": "Load complete.",

        # New Additions
        "LOGS": "LOGS", "EQUIP": "EQUIP", "QUICK SLOTS": "QUICK SLOTS", "SKILLS": "SKILLS", "ACTIVE EFFECTS": "ACTIVE EFFECTS",
        "Head": "Head", "Body": "Body", "Hand1": "Hand1", "Hand2": "Hand2", "Gloves": "Gloves", "Boots": "Boots", "Neck": "Neck", "Ring1": "Ring1", "Ring2": "Ring2",
        "recovered": "recovered", "HP": "HP", "MP": "MP", "Gold": "Gold", "Log": "Log", "Name": "Name", "Close": "Close",
        "Experience": "Experience", "Stat Points": "Stat Points", "Attack": "Attack", "Defense": "Defense",
        "이름": "Name", "경험치": "Experience", "스탯 포인트": "Stat Points",
        "공격력": "Attack", "방어력": "Defense", "Dungeon Map": "Dungeon Map", "Player Condition": "Player Condition",
        "마력을 충전할 지팡이를 들고 있지 않습니다.": "You are not holding a staff to recharge.",
        "시공간이 뒤틀리며 무작위 위치로 이동했습니다! ({}, {})": "Spacetime warped, moving to a random location! ({}, {})",
        "이동할 수 있는 빈 공간이 없습니다.": "No empty space to move to.",
        "체력을 {} 회복했습니다!": "Recovered {} HP!",
        "'{}'가 분노를 폭발시킵니다! (지속 {}초)": "'{}' explodes in fury! (Duration {}s)",
        "'{}'!! 번개 폭발이 주변을 뒤덮습니다!": "'{}'!! A lightning explosion covers the area!",
        "'{}'!!! 종말의 불꽃이 모든 것을 뒤덮습니다!": "'{}'!!! Flames of apocalypse cover everything!",
        "'{}'!! 수호자 포탑을 소환합니다!": "'{}'!! Summoning a Guardian Sentry!",
        "'{}'!! 강력한 진흙 골렘을 소환합니다!": "'{}'!! Summoning a powerful Clay Golem!",
        "'{}'!! 서늘한 번개 파동이 퍼져나갑니다!": "'{}'!! A cold lightning pulse spreads out!",
        "상인을 만났습니다. (거래 가능)": "Met a Merchant. (Trade available)",
        "{}와 충돌했습니다. 전투가 시작됩니다.": "Collided with {}. Combat starts.",
        "알 수 없는 엔티티와 충돌했습니다.": "Collided with an unknown entity.",
        "충돌 발생: {}": "Collision occurred: {}",
        "사용할 오일을 선택하세요:": "Select oil to use:",
        "(사용 가능한 오일이 없습니다)": "(No eligible oils available)",
        "특별한 제물을 바치시겠습니까?": "Would you like to offer a special sacrifice?",
        "제물을 바치면 강화 성공률이 오르거나": "Offering a sacrifice can increase success rate",
        "아이템 파괴를 방지할 수 있습니다.": "or prevent item destruction.",
        "봉납할 제물을 선택하세요:": "Select a sacrifice to offer:",
        "(보유 중인 제물이 없습니다. 그대로 강화하시겠습니까?)": "(No eligible sacrifices found. Proceed with enhancement?)",
        "[ENTER]를 누르면 제물 없이 강화를 시작합니다.": "Press [ENTER] to start enhancement without a sacrifice.",
        " [↑/↓] 선택  [ENTER] 감정  [ESC] 취소 ({}/{}) ": " [↑/↓] Select  [ENTER] Identify  [ESC] Cancel ({}/{}) ",
        
        # Game Start Messages
        "WASD나 방향키로 이동하고 몬스터와 부딪혀 전투하세요.": "Use WASD or arrow keys to move and bump into monsters to fight.",
        
        # Inventory UI
        "선택:": "Select:",
        "이름:": "Name:",
        "설명:": "Desc:",
        "필요 레벨:": "Req Lv:",
        "공격:": "ATK:",
        "방어:": "DEF:",
        "사거리:": "Range:",
        "효과:": "Effect:",
        
        # Character Sheet
        "STR (힘)": "STR (Str)",
        "MAG (마력)": "MAG (Mag)",
        "DEX (민첩)": "DEX (Dex)",
        "VIT (활력)": "VIT (Vit)",
        "Points:": "Points:",
        
        # Shop UI
        "사기 (BUY)": "BUY",
        "팔기 (SELL)": "SELL",
        "소지 골드:": "Gold:",
        "구매": "Buy",
        "판매": "Sell",
        "[←/→] 탭 전환  [↑/↓] 선택  [ENTER]": "[←/→] Tab  [↑/↓] Select  [ENTER]",
        " [B] 뒤로/닫기": " [B] Back/Close",
        
        # Shrine UI
        "강화할 장비 선택": "Select Equipment to Enhance",
        "[ENTER] 강화  [ESC] 취소": "[ENTER] Enhance  [ESC] Cancel",
        
        # Inventory Tabs
        "아이템": "Items",
        "장비": "Equipment",
        "스크롤": "Scrolls",
        "스킬": "Skills",
        
        # Stat Descriptions
        "공격력 / 무기효율": "Attack / Weapon Efficiency",
        "최대마력 / 마법효율": "Max Mana / Magic Efficiency",
        "방어력 / 명중률 / 치명타": "Defense / Accuracy / Critical",
        "최대체력 / 생존력": "Max HP / Survivability",
        
        # Control Guides
        "[↑/↓] 선택  [→/ENTER] 포인트 투자  [C/ESC] 닫기": "[↑/↓] Select  [→/ENTER] Invest  [C/ESC] Close",
        "[←/→] 탭  [↑/↓] 선택  [ENTER/E] 등록/해제  [X] 스킬 잊기  [B] 닫기": "[←/→] Tab  [↑/↓] Select  [ENTER/E] Assign  [X] Forget  [B] Close",
        "[←/→] 탭  [↑/↓] 선택  [E] 퀴슬롯 등록  [ENTER] 사용/장착  [B] 닫기": "[←/→] Tab  [↑/↓] Select  [E] Quickslot  [ENTER] Use/Equip  [B] Close",
        "[↑/↓] 선택  [ENTER] 다음  [B] 뒤로  [Q] 닫기": "[↑/↓] Select  [ENTER] Next  [B] Back  [Q] Close",
        "[←/→] 선택  [ENTER] 확인  [B] 뒤로  [Q] 닫기": "[←/→] Select  [ENTER] Confirm  [B] Back  [Q] Close",
        "[↑/↓] 선택  [ENTER] 강화 실행  [B] 뒤로  [Q] 닫기": "[↑/↓] Select  [ENTER] Enhance  [B] Back  [Q] Close",
        "{}의 전리품: {}이(가) 떨어졌습니다!": "{}'s Loot: {} dropped!",
        "{}의 효과로 능력이 향상되었습니다!": "Attributes increased by effect of {}!",
        "'{}' 발동! (Lv.{}, {})": "'{}' Activated! (Lv.{}, {})",
        "마법 장막이 생겨나 데미지를 마나로 흡수합니다! (지속 {}초)": "A magic veil appears, absorbing damage into mana! (Duration {}s)",
        "차원 문을 통해 이동했습니다! ({}, {})": "Moved through a dimensional gate! ({}, {})",
        "!!! '{}' 폭발 !!!": "!!! '{}' Explosion !!!",
        "[{}]의 내구도를 {} 회복했습니다.": "Recovered {} durability for [{}].",
        "함정 {}개를 안전하게 해제했습니다! (+{}XP){}(성공률 {}%)": "Safely disarmed {} traps! (+{}XP){}(Success rate {}%)",
        "해제에 실패하여 함정 {}개가 발동되었습니다! (피해 감쇄 {}%)": "Failed to disarm, {} traps triggered! (Damage reduction {}%)",
        "주변에 해제할 함정이 발견되지 않았습니다.": "No traps found nearby to disarm.",
        "지팡이에 마력을 {}회 충전했습니다! ({}/{})": "Charged staff with {} mana! ({}/{})",
        "지팡이의 마력이 이미 가득 차 있습니다.": "Staff's mana is already full.",
        "차를 충전할 지팡이를 들고 있지 않습니다.": "You are not holding a staff to recharge.",
        "시공간이 뒤틀리며 무작위 위치로 이동했습니다! ({}, {})": "Spacetime warped, moving to a random location! ({}, {})",
        "이동할 수 있는 빈 공간이 없습니다.": "No empty space to move to.",
        "체력을 {} 회복했습니다!": "Recovered {} HP!",
        "'{}'가 분노를 폭발시킵니다! (지속 {}초)": "'{}' explodes in fury! (Duration {}s)",
        "'{}'!! 번개 폭발이 주변을 뒤덮습니다!": "'{}'!! A lightning explosion covers the area!",
        "'{}'!!! 종말의 불꽃이 모든 것을 뒤덮습니다!": "'{}'!!! Flames of apocalypse cover everything!",
        "'{}'!! 수호자 포탑을 소환합니다!": "'{}'!! Summoning a Guardian Sentry!",
        "'{}'!! 강력한 진흙 골렘을 소환합니다!": "'{}'!! Summoning a powerful Clay Golem!",
        "'{}'!! 서늘한 번개 파동이 퍼져나갑니다!": "'{}'!! A cold lightning pulse spreads out!",
        "상인을 만났습니다. (거래 가능)": "Met a Merchant. (Trade available)",
        "{}와 충돌했습니다. 전투가 시작됩니다.": "Collided with {}. Combat starts.",
        "알 수 없는 엔티티와 충돌했습니다.": "Collided with an unknown entity.",
        "충돌 발생: {}": "Collision occurred: {}",
        "사용할 오일을 선택하세요:": "Select oil to use:",
        "(사용 가능한 오일이 없습니다)": "(No eligible oils available)",
        "특별한 제물을 바치시겠습니까?": "Would you like to offer a special sacrifice?",
        "제물을 바치면 강화 성공률이 오르거나": "Offering a sacrifice can increase success rate",
        "아이템 파괴를 방지할 수 있습니다.": "or prevent item destruction.",
        "봉납할 제물을 선택하세요:": "Select a sacrifice to offer:",
        "(보유 중인 제물이 없습니다. 그대로 강화하시겠습니까?)": "(No eligible sacrifices found. Proceed with enhancement?)",
        "[ENTER]를 누르면 제물 없이 강화를 시작합니다.": "Press [ENTER] to start enhancement without a sacrifice.",
        " [↑/↓] 선택  [ENTER] 감정  [ESC] 취소 ({}/{}) ": " [↑/↓] Select  [ENTER] Identify  [ESC] Cancel ({}/{}) ",
        
        # Dungeon Messages
        "던전 {}층 [{}]에 입장했습니다.": "Entered Dungeon Floor {} [{}].",
        "[경고] 강력한 보스의 기운이 느껴집니다!": "[WARNING] A powerful boss presence detected!",
        "[경고] {}이(가) 나타났습니다!": "[WARNING] {} has appeared!",
        "강력한 적": "Powerful Enemy",
        "{}의 환영": "{}'s Illusion",
        
        # Entity Types
        "상인": "Merchant",
        "신전": "Shrine",
        
        # Item Names (for shop defaults)
        "체력 물약": "Health Potion",
        "마력 물약": "Mana Potion",
        "확인 스크롤": "Identify Scroll",
        
        # System Messages (Dynamic)
        "전신이 석화되어 움직일 수 없습니다!": "You are petrified and cannot move!",
        "몸이 움직이지 않습니다... (기절 중)": "You cannot move... (Stunned)",
        "깊은 잠에 빠져 움직일 수 없습니다... (수면 중)": "You cannot move... (Deep Sleep)",
        "지팡이에 충전된 '{}'을(를) 방출하여 자신을 치유합니다!": "You release the charged '{}' from your staff to heal yourself!",
        "지팡이에 충전된 '{}'을(를) 방출합니다!": "You release the charged '{}' from your staff!",
        "주변을 살펴봅니다.": "You look around.",
        "{}의 시체를 살펴봅니다...": "You examine the corpse of {}...",
        "지상으로 나가는 출구는 막혀있습니다.": "The exit to the surface is blocked.",
        "제자리에서 대기합니다.": "You wait.",
        "탈진하여 쓰러졌습니다! (Stamina 0)": "You collapsed from exhaustion! (Stamina 0)",
        "다음 층으로 연결되는 계단입니다. [ENTER] 키를 눌러 내려가시겠습니까?": "Stairs down to the next floor. Press [ENTER] to descend?",
        "이전 층으로 연결되는 계단입니다. [ENTER] 키를 눌러 올라가시겠습니까?": "Stairs up to the previous floor. Press [ENTER] to ascend?",
        "숨겨진 무언가를 발견했습니다!": "You found something hidden!",
        "{}의 강력한 기운이 방출됩니다!": "A powerful aura exudes from {}!",
        "!!! {}이(가) 분노하여 더욱 강력해집니다! !!!": "!!! {} becomes enraged and grows stronger! !!!",
        "{}이(가) {}.": "{} is {}.",
        "쿠쿠쿵! 어딘가에서 거대한 문이 열리는 소리가 들립니다!": "Rumble! You hear a massive door opening somewhere!",
        "레버를 당기자 함정이 발동했습니다! 폭발이 일어납니다!": "A trap triggers as you pull the lever! An explosion occurs!",
        "폭발로 인해 {}의 피해를 입었습니다! (HP {}%)": "You took {} damage from the explosion! (HP {}%)",
        "문에서 독침이 튀어나왔습니다!": "Poison needles shot out from the door!",
        "'{}'이(가) 강력한 포효와 함께 지원군을 부릅니다!": "'{}' calls for reinforcements with a mighty roar!",
        "!!! {}이(가) {}의 환영을 불러냅니다! !!!": "!!! {} summons the illusion of {}! !!!",
        "보물상자가 갑자기 몬스터로 변했습니다! 기습 공격을 받았습니다!": "The chest suddenly turned into a monster! You were ambushed!",
        "{}와 {}가 충돌하여 서로 {}의 피해를 입었습니다!": "{} and {} collided, dealing {} damage to each other!",
        "{}가 뒤로 밀려났습니다!": "{} was knocked back!",
        "{}가 벽에 부딪혀 {}의 추가 피해를 입었습니다!": "{} hit the wall and took {} extra damage!",
        "{}가 벽에 부딪혀 피해를 입었습니다!": "{} hit the wall and took damage!",
        "체력이 1 회복되었습니다.": "Recovered 1 HP.",
        "마력이 1 회복되었습니다.": "Recovered 1 MP.",
        "이전 보스 1마리 소환": "Summon previous boss", # Not used directly in message but good to have
        "알 수 없는 엔티티와 충돌했습니다.": "Collided with unknown entity.",
        "충돌 발생: {}": "Collision: {}",
        "상인을 만났습니다. (거래 가능)": "You met a Merchant. (Trade available)",
        "{}와 충돌했습니다. 전투가 시작됩니다.": "Collided with {}. Combat starts.",
        "{}이(가) 깊은 잠에 빠졌습니다.": "{} fell into a deep sleep.",
        "{}이(가) 돌로 변했습니다!": "{} turned into stone!",
        "{}이(가) 독에 중독되었습니다!": "{} is poisoned!",
        
        # Additional Shop & Engine Messages
        "상점에 오신 것을 환영합니다!": "Welcome to the shop!",
        "저장하고 메인 메뉴로 돌아갑니다...": "Saving and returning to main menu...",
        "몸이 움직이지 않아 아이템을 조작할 수 없습니다!": "You cannot manipulate items while immobilized!",
        "{}을(를) 인벤토리에서 찾을 수 없습니다.": "Could not find {} in inventory.",
        "{} 스킬 데이터가 없습니다.": "No skill data for {}.",
        "{}번 스킬 슬롯이 비어있습니다.": "Skill slot {} is empty.",
        "아이템 퀵슬롯": "Item Quickslot",
        "스킬 퀵슬롯": "Skill Quickslot",
        "방향을 선택하세요...": "Select a direction...",
        "상성 우위! +{}%": "Advantage! +{}%",
        "상성 열위.. -{}%": "Disadvantage.. -{}%",

        # Shrine & Enhancement Messages
        "신전의 축복을 선택하세요:": "Choose the Shrine's blessing:",
        "[↑/↓] 선택  [ENTER] 확인  [Q] 나가기": "[↑/↓] Select  [ENTER] Confirm  [Q] Exit",
        "강화할 장비를 선택하세요:": "Select equipment to enhance:",
        "[↑/↓] 선택  [ENTER] 다음  [B] 뒤로  [Q] 닫기": "[↑/↓] Select  [ENTER] Next  [B] Back  [Q] Close",
        "사용할 오일을 선택하세요:": "Select oil to use:",
        "[←/→] 선택  [ENTER] 확인  [B] 뒤로  [Q] 닫기": "[←/→] Select  [ENTER] Confirm  [B] Back  [Q] Close",
        "봉납할 제물을 선택하세요:": "Select an offering to sacrifice:",
        "[↑/↓] 선택  [ENTER] 강화 실행  [B] 뒤로  [Q] 닫기": "[↑/↓] Select  [ENTER] Enhance  [B] Back  [Q] Close",
        "이미 최대 강화 등급입니다!": "Already at maximum enhancement level!",
        "강화 성공! {}": "Enhancement Success! {}",
        "강화 실패... {}의 내구도가 감소했습니다.": "Enhancement Failed... {} durability decreased.",
        "강화 실패! {}이(가) 파손되었습니다!": "Enhancement Failed! {} was damaged!",
        "강화 실패! {}이(가) 산산조각 났습니다...": "Enhancement Failed! {} was shattered...",

        # System & Combat Messages
        "{}가 분노에 이끌려 달려옵니다!": "{} rushes forward in a rage!",
        "{}가 갑자기 이동했습니다!": "{} moved suddenly!",
        "도살자: \"Ah... Fresh Meat!\"": "Butcher: \"Ah... Fresh Meat!\"",
        "{}가 '{}'을(를) 모방하여 시전합니다!": "{} mimics and casts '{}'!",
        "도살자가 분노하여 지원군을 부릅니다!": "The Butcher calls for reinforcements in fury!",
        "해골 왕이 영원한 충성을 요구합니다!": "The Skeleton King demands eternal loyalty!",
        "{}가 지원군을 부릅니다!": "{} calls for reinforcements!",
        "해골 왕이 죽은 자를 다시 일으켜 세웁니다!": "The Skeleton King raises the dead!",
        "디아블로가 파멸의 화염(Apocalypse)을 시전합니다!": "Diablo casts Apocalypse!",
        "화염이 {}을 덮쳐 {}의 피해를 입혔습니다!": "The flames engulfed {} for {} damage!",
        "'{}'의 원거리 공격!": "Ranged attack of '{}'!",
        "공격이 벽에 막혔습니다.": "Attack blocked by wall.",
        "{source}에서 {}을(를) 획득했습니다!": "Obtained {} from {source}!",
        "{source}를 살펴봅니다... 아무것도 발견하지 못했습니다.": "Examines {source}... Found nothing.",
        "도살자의 식칼에 베여 과다출혈이 발생합니다!": "The Butcher's cleaver causes excessive bleeding!",
        "{}이(가) 출혈 상태가 되었습니다!": "{} is now bleeding!",
        "마법 장막이 {}의 피해를 흡수했습니다! (남은 MP: {})": "Mana Shield absorbed {} damage! (Remaining MP: {})",
        "'{}'이(가) 강력한 충격으로 경직되었습니다!": "'{}' is stunned by a powerful impact!",
        "[경고] {}의 {}이(가) 파손되었습니다!": "[Warning] {}'s {} was damaged!",
        "{}이(가) 충격으로 기절했습니다!": "{} is stunned by the impact!",
        "주변의 적들이 공격에 휘말립니다!": "Nearby enemies are caught in the attack!",
        "{}이(가) 공격을 받아 잠에서 깨어났습니다!": "{} woke up from the attack!",
        "{}이(가) 쓰러졌습니다!": "{} has fallen!",
        "경험치 {}를 획득했습니다.": "Gained {} experience.",
        "{}이(가) 강력한 포효와 함께 지원군을 부릅니다!": "{} calls for reinforcements with a mighty roar!",
        "기술이 준비되지 않았습니다! ({}초)": "Skill is not ready! ({}s)",
        "지팡이에 '{}' 마력을 충전했습니다!": "Charged staff with '{}' power!",
        "충전을 취소했습니다.": "Recharge canceled.",
        "수리할 장비가 없습니다.": "No equipment to repair.",
        "수리가 필요한 아이템이 없습니다.": "No items need repair.",
        "'{}' 수리에 성공했습니다!": "Successfully repaired '{}'!",
        "'{}' 수리에 실패했습니다...": "Failed to repair '{}'...",
        "수리를 취소했습니다.": "Repair canceled.",
        "알 수 없는 스킬입니다: {}": "Unknown skill: {}",
        "몸이 움직이지 않아 퀵슬롯을 사용할 수 없습니다!": "You cannot use quickslots while immobilized!",
        "{}을(를) 인벤토리에서 찾을 수 없습니다.": "Could not find {} in inventory.",
        "{}번 퀵슬롯이 비어있습니다.": "Quickslot {} is empty.",
        "식별되지 않은 아이템은 사용할 수 없습니다.": "Unidentified items cannot be used.",
        "레벨이 부족하여 '{}'을(를) 읽을 수 없습니다. (필요: Lv.{}, 현재: Lv.{})": "You need a higher level to read '{}'. (Need: Lv.{}, Current: Lv.{})",
        "이 책은 가르침이 없습니다: {}": "This book has no teachings: {}",
        "이 서적의 내용은 {}만이 이해할 수 있습니다.": "Only {} can understand the contents of this book.",
        "존재하지 않는 기술의 비급서입니다: {}": "This manual contains a non-existent skill: {}",
        "식별할 미확인 아이템이 없습니다.": "No unidentified items to identify.",
        "강화할 장비를 선택하세요.": "Select equipment to enhance.",
        "'{}' 스킬을 잊었습니다.": "Forgot skill '{}'.",
        "{}의 장착을 해제했습니다.": "Unequipped {}.",
        "식별되지 않은 아이템은 장착할 수 없습니다.": "Unidentified items cannot be equipped.",
        "레벨이 부족하여 장착할 수 없습니다. (필요: Lv.{})": "Level too low to equip. (Required: Lv.{})",
        "{}을(를) 장착했습니다.": "Equipped {}.",
        "강화를 취소했습니다.": "Enhancement canceled.",
        "{}이(가) 강화되었습니다!": "{} has been enhanced!",
        "이 아이템에는 사용할 수 없습니다.": "Cannot use on this item.",
        "빈 슬롯입니다.": "Empty slot.",
        "축복을 다한 신전이 요란한 소리를 내며 무너져 내립니다!": "The shrine, having spent its blessing, collapses with a loud noise!",
        "[오일] {}의 날에 차가운 광기가 서립니다! (공격력 +{})": "[Oil] A cold madness seeps into the blade of {}! (Attack +{})",
        "[오일] 무기에 정밀한 마법의 문양이 새겨지며 목표를 쫓습니다. (명중률 +{}%)": "[Oil] Precise magical patterns are etched onto the weapon, seeking the target. (Accuracy +{}%)",
        "[오일] 갑옷의 표면이 강철보다 단단한 질감으로 변합니다. (방어력 +{})": "[Oil] The armor's surface becomes harder than steel. (Defense +{})",
        "[오일] {}의 구조가 강화되어 더욱 긴 시간 견딜 수 있게 되었습니다. (최대 내구도 +{})": "[Oil] The structure of {} has been reinforced, allowing it to endure much longer. (Max Durability +{})",
        "[오일] 불멸의 금속이 덧대어져 파괴 불가능에 가까운 강도를 얻었습니다! (최대 내구도 +{})": "[Oil] Immortal metal is added, giving it nearly indestructible strength! (Max Durability +{})",
        "[오일] 장비의 무게가 마치 깃털처럼 가벼워집니다. (요구 레벨 -{})": "[Oil] The equipment's weight becomes as light as a feather. (Required Level -{})",
        "[오일] 대장장이의 정수가 흐르며 {}의 모든 균열이 메워집니다!": "[Oil] Blacksmith's essence flows, filling all cracks in {}!",
        "[제물] 악마의 피가 갈구하듯 끓어오르며 강화의 성공을 이끕니다... (+10%)": "[Sacrifice] Demon's blood boils with desire, leading to enhancement success... (+10%)",
        "[제물] 눈부신 천사의 깃털이 대상을 감싸 안아 파괴로부터 보호합니다.": "[Sacrifice] Dazzling angel feathers envelop the target, protecting it from destruction.",
        "[제물] 룬석이 공명하며 아이템에 잠재된 마법의 흐름을 뒤바꿉니다!": "[Sacrifice] The runestone resonates, altering the latent magical flow within the item!",
        "[제물] 어둠의 수정이 {}의 본질을 뒤흔들어 마법의 물건으로 승급시킵니다!": "[Sacrifice] The dark crystal shakes the essence of {}, promoting it to a magical item!",
        "이미 최대 강화 등급입니다! (+10)": "Already at maximum enhancement level! (+10)",
        "[성공] 빛무리가 걷히고 더욱 강력해진 {}이(가) 모습을 드러냅니다!": "[Success] The crowd of light clears, and a more powerful {} reveals itself!",
        "강화 실패! 하지만 제물 덕분에 {}의 파괴를 면했습니다!": "Enhancement failed! But thanks to the sacrifice, {} was spared from destruction!",
        "과거의 고기여... 나를 도우라!": "Meat of the past... help me!",
        "몸이 움직이지 않아 퀵슬롯을 사용할 수 없습니다!": "You cannot use quickslots while immobilized!",
        "{}을(를) 인벤토리에서 찾을 수 없습니다.": "Could not find {} in inventory.",
        "{}번 퀵슬롯이 비어있습니다.": "Quickslot {} is empty.",
        "식별되지 않은 아이템은 사용할 수 없습니다.": "Unidentified items cannot be used.",
        "레벨이 부족하여 '{}'을(를) 읽을 수 없습니다. (필요: Lv.{}, 현재: Lv.{})": "You need a higher level to read '{}'. (Need: Lv.{}, Current: Lv.{})",
        "이 책은 가르침이 없습니다: {}": "This book has no teachings: {}",
        "이 서적의 내용은 {}만이 이해할 수 있습니다.": "Only {} can understand the contents of this book.",
        "존재하지 않는 기술의 비급서입니다: {}": "This manual contains a non-existent skill: {}",
        "식별할 미확인 아이템이 없습니다.": "No unidentified items to identify.",
        "강화할 장비를 선택하세요.": "Select equipment to enhance.",
        "'{}' 스킬을 잊었습니다.": "Forgot skill '{}'.",
        "{}의 장착을 해제했습니다.": "Unequipped {}.",
        "식별되지 않은 아이템은 장착할 수 없습니다.": "Unidentified items cannot be equipped.",
        "레벨이 부족하여 장착할 수 없습니다. (필요: Lv.{})": "Level too low to equip. (Required: Lv.{})",
        "{}을(를) 장착했습니다.": "Equipped {}.",
        "강화를 취소했습니다.": "Enhancement canceled.",
        "{}이(가) 강화되었습니다!": "{} has been enhanced!",
        "이 아이템에는 사용할 수 없습니다.": "Cannot use on this item.",
        "빈 슬롯입니다.": "Empty slot.",
        "축복을 다한 신전이 요란한 소리를 내며 무너져 내립니다!": "The shrine, having spent its blessing, collapses with a loud noise!",
        "[오일] {}의 날에 차가운 광기가 서립니다! (공격력 +{})": "[Oil] A cold madness seeps into the blade of {}! (Attack +{})",
        "[오일] 무기에 정밀한 마법의 문양이 새겨지며 목표를 쫓습니다. (명중률 +{}%)": "[Oil] Precise magical patterns are etched onto the weapon, seeking the target. (Accuracy +{}%)",
        "[오일] 갑옷의 표면이 강철보다 단단한 질감으로 변합니다. (방어력 +{})": "[Oil] The armor's surface becomes harder than steel. (Defense +{})",
        "[오일] {}의 구조가 강화되어 더욱 긴 시간 견딜 수 있게 되었습니다. (최대 내구도 +{})": "[Oil] The structure of {} has been reinforced, allowing it to endure much longer. (Max Durability +{})",
        "[오일] 불멸의 금속이 덧대어져 파괴 불가능에 가까운 강도를 얻었습니다! (최대 내구도 +{})": "[Oil] Immortal metal is added, giving it nearly indestructible strength! (Max Durability +{})",
        "[오일] 장비의 무게가 마치 깃털처럼 가벼워집니다. (요구 레벨 -{})": "[Oil] The equipment's weight becomes as light as a feather. (Required Level -{})",
        "[오일] 대장장이의 정수가 흐르며 {}의 모든 균열이 메워집니다!": "[Oil] Blacksmith's essence flows, filling all cracks in {}!",
        "[제물] 악마의 피가 갈구하듯 끓어오르며 강화의 성공을 이끕니다... (+10%)": "[Sacrifice] Demon's blood boils with desire, leading to enhancement success... (+10%)",
        "[제물] 눈부신 천사의 깃털이 대상을 감싸 안아 파괴로부터 보호합니다.": "[Sacrifice] Dazzling angel feathers envelop the target, protecting it from destruction.",
        "[제물] 룬석이 공명하며 아이템에 잠재된 마법의 흐름을 뒤바꿉니다!": "[Sacrifice] The runestone resonates, altering the latent magical flow within the item!",
        "[제물] 어둠의 수정이 {}의 본질을 뒤흔들어 마법의 물건으로 승급시킵니다!": "[Sacrifice] The dark crystal shakes the essence of {}, promoting it to a magical item!",
        "이미 최대 강화 등급입니다! (+10)": "Already at maximum enhancement level! (+10)",
        "[성공] 빛무리가 걷히고 더욱 강력해진 {}이(가) 모습을 드러냅니다!": "[Success] The crowd of light clears, and a more powerful {} reveals itself!",
        "강화 실패! 하지만 제물 덕분에 {}의 파괴를 면했습니다!": "Enhancement failed! But thanks to the sacrifice, {} was spared from destruction!",
        "과거의 고기여... 나를 도우라!": "Meat of the past... help me!",
        "큰 충격과 함께 뒤로 밀려납니다!": "You are pushed back with a powerful impact!",
        "!!! 도살자가 미친 듯이 돌진합니다! !!!": "!!! The Butcher charges madly! !!!",
        "도살자의 돌진에 치여 큰 피해를 입었습니다!": "You took heavy damage from the Butcher's charge!",
        "도살자가 벽에 들이받고 기절했습니다!": "The Butcher hit the wall and is stunned!",
        "{}이(가) 해골 군단을 소환합니다!": "{} summons an army of skeletons!",
        "!!! {}의 마법으로 전신이 석화되었습니다! !!!": "!!! Your entire body has been petrified by {}'s magic! !!!",
        "!!! 리치 왕의 시선에 몸이 더욱 굳어갑니다! (석화 {}스택) !!!": "!!! Your body stiffens further under the Lich King's gaze! (Petrify {} stacks) !!!",
        "!!! 이미 완전히 석화된 상태입니다! !!!": "!!! You are already completely petrified! !!!",
        "!!! 리치 왕의 시선이 당신을 굳게 만듭니다! (석화 1스택) !!!": "!!! The Lich King's gaze makes you stiffen! (Petrify 1 stack) !!!",
        "!!! 대지의 저주가 당신의 발을 묶습니다! !!!": "!!! The Curse of the Earth binds your feet! !!!",
        "{}들이 보스의 부름에 응답하여 나타납니다!": "{} appear in response to the boss's call!",
        "잠겨있습니다. 열쇠가 필요합니다.": "It is locked. A key is required.",
        "{}이(가) {}.": "{} is {}.",
        "쿠쿠쿵! 어딘가에서 거대한 문이 열리는 소리가 들립니다!": "Ku-ku-kung! The sound of a giant door opening is heard from somewhere!",
        "레버를 당기자 함정이 발동했습니다! 폭발이 일어납니다!": "Pulling the lever triggered a trap! An explosion occurs!",
        "폭발으로 인해 {}의 피해를 입었습니다! (HP {}%)": "Took {} damage from the explosion! (HP {}%)",
        "문에서 독침이 튀어나왔습니다!": "A poison needle popped out of the door!",
        "{}이(가) 중독되었습니다!": "{} has been poisoned!",
        "문이 폭발했습니다!": "The door exploded!",
        "{}이(가) {}의 피해를 입었습니다! (HP {}%, 감쇄 {}%)": "{} took {} damage! (HP {}%, Reduction {}%)",
        "문에서 사악한 기운이 뿜어져 나옵니다!": "Evil energy emanates from the door!",
        "{}이(가) 저주에 걸렸습니다!": "{} has been cursed!",
        "문에서 독가스가 분출됩니다!": "Poison gas is being emitted from the door!",
        "{}이(가) 독가스에 중독되었습니다!": "{} has been poisoned by the gas!",
        "게임 저장 실패: {}": "Failed to save game: {}",
        "{}... (던전 {}층)": "{}... (Dungeon Floor {})",
        "신성한 기운이 느껴집니다...": "A divine aura is felt...",
        "{}을(를) {} 골드에 판매했습니다.": "Sold {} for {} gold.",
        "판매할 아이템이 없습니다.": "No items to sell.",
        "{}을(를) {} 골드에 구매했습니다!": "Purchased {} for {} gold!",
        "골드가 부족합니다!": "Not enough gold!",
        "{}을(를) {} {}번에서 해제했습니다.": "Unequipped {} from {} {}.",
        "{}을(를) {} {}번에 등록했습니다.": "Registered {} to {} {}.",
        "{}이 가득 찼습니다!": "{} is full!",
        "강화 실패... {}의 내구도가 감소했습니다.": "Enhancement failed... {} durability decreased.",
        "강화 실패! {}이(가) 파손되었습니다!": "Enhancement failed! {} was damaged!",
        "강화 실패! {}이(가) 산산조각 났습니다...": "Enhancement failed! {} was shattered...",
        "이미 최대 강화 등급입니다! (+10)": "Already at maximum enhancement level! (+10)",
        "[성공] 빛무리가 걷히고 더욱 강력해진 {}이(가) 모습을 드러냅니다!": "[Success] The crowd of light clears, and a more powerful {} reveals itself!",
        "{}이(가) 독가스에 중독되었습니다!": "{} has been poisoned by gas!",
        "{} 효과가 만료되었습니다.": "{} effect expired.",
        "레벨업! 현재 레벨: {}": "Level Up! Current Level: {}",
        "체력과 마력이 모두 회복되었습니다!": "HP and MP fully recovered!",
        "보너스 스탯 포인트 +{} 획득!": "Bonus Stat Points +{} acquired!",
        "!!! {}이(가) {}의 마법으로 전신이 석화되었습니다! !!!": "!!! {} is petrified by {}'s magic! !!!",
        "!!! {}이(가) 해골 군단을 소환합니다!": "!!! {} summons a Skeleton Army!",
        "!!! {} : {} !!!": "!!! {} : {} !!!", # Generic boss shout
        "!!! {}의 광역 강타! !!!": "!!! {}'s AOE Smite! !!!",
        "!!! {}의 시선에 몸이 더욱 굳어갑니다! (석화 {}스택) !!!": "!!! {}'s gaze stiffens your body! (Petrify Stack {}) !!!",
        "!!! 이미 완전히 석화된 상태입니다! !!!": "!!! You are already fully petrified! !!!",
        "!!! 리치 왕의 시선이 당신을 굳게 만듭니다! (석화 1스택) !!!": "!!! The Lich King's gaze stiffens you! (Petrify Stack 1) !!!",
        "!!! 대지의 저주가 당신의 발을 묶습니다! !!!": "!!! Earth's Curse binds your feet! !!!",
        "{}의 전리품: {}이(가) 떨어졌습니다!": "{}'s Loot: {} dropped!",
        "!!! 던전을 정복했습니다 !!!": "!!! Dungeon Conquered !!!",
        "!!! {}(으)로 가는 계단이 나타났습니다 !!!": "!!! Stairs to {} appeared !!!",
        "도살자의 돌진에 치여 큰 피해를 입었습니다!": "You took massive damage from The Butcher's charge!",
        "도살자가 벽에 들이받고 기절했습니다!": "The Butcher hit a wall and is stunned!",
        "갈고리에 끌려가 기절했습니다!": "Dragged by the hook and stunned!",
        "큰 충격과 함께 뒤로 밀려납니다!": "Knocked back with a massive impact!",
        "!!! 도살자의 강력한 내려치기! !!!": "!!! The Butcher's Mighty Slam! !!!",
        "!!! 도살자가 미친 듯이 돌진합니다! !!!": "!!! The Butcher charges madly! !!!",
        "!!! 도살자가 피 묻은 갈고리를 던집니다! !!!": "!!! The Butcher throws a bloody hook! !!!",
        "{}이(가) 당신을 향해 급격히 돌진합니다!": "{} dashes towards you!",
        "{}의 대회전 공격!": "{}'s Whirlwind Attack!",
        "환영의 일격이라 위력이 약합니다.": "Illusion's strike is weaker.",
        "레버를 당기자 함정이 발동했습니다! 폭발이 일어납니다!": "Pulling the lever triggered a trap! Explosion!",
        "폭발로 인해 {}의 피해를 입었습니다! (HP {}%)": "Took {} damage from explosion! (HP {}%)",
        "공격 방향을 선택하세요... [Space] 취소": "Select attack direction... [Space] to cancel",
        "공격 모드 해제.": "Attack mode disabled.",
        "'{}'의 공격이 '{}'에게 빗나갔습니다! (확률: {}%)": "'{}'s attack missed '{}'! (Chance: {}%)",
        "'{}'이(가) '{}'의 공격을 가뿐히 받아냈습니다!": "'{}' easily blocked '{}'s attack!",
        "'{}'의 {}! '{}'에게 {} 데미지!{}": "'{}'s {}! Dealt {} damage to '{}'!{}",
        "'{}'의 공격! '{}'에게 {} 데미지!{}": "'{}' attacks! Dealt {} damage to '{}'!{}",
        
        # Shrine
        "신성한 힘이 당신을 완전히 회복시켰습니다!": "Divine power has fully restored you!",
        "이미 최대 강화 등급입니다!": "Already at maximum enhancement level!",
        "강화 성공! {}": "Enhancement Successful! {}",
        "강화 실패... {}의 내구도가 감소했습니다.": "Enhancement Failed... {} durability decreased.",
        "강화 실패! {}이(가) 파손되었습니다!": "Enhancement Failed! {} is broken!",
        "강화 실패! {}이(가) 산산조각 났습니다...": "Enhancement Failed! {} shattered...",
        
        # UI & Misc
        "필요 레벨:": "Req Level:",
        "소지 골드:": "Gold:",
        "Trap ID '{}'에 해당하는 함정 정의를 찾을 수 없습니다.": "Trap definition for ID '{}' not found.",
        
        "GAME OVER! 저장된 데이터가 삭제됩니다.": "GAME OVER! Save data will be deleted.",
    }
}

def _(text):
    """지정된 언어에 맞춰 텍스트를 번역하거나 원본을 반환합니다."""
    lang = getattr(config, 'LANGUAGE', 'ko')
    
    trans = TRANSLATIONS.get(lang, {})
    if text in trans:
        return trans[text]
    
    return text

L = _ # Alias for easier access

def get_data_path(file_name, original_path=None):
    """현재 언어 설정을 고려하여 데이터 파일 경로를 반환합니다."""
    lang = getattr(config, 'LANGUAGE', 'ko')
    
    if original_path is None:
        original_path = os.path.join(os.path.dirname(__file__), "data")
    
    if lang == "en":
        en_path = os.path.join(original_path, "en", file_name)
        if os.path.exists(en_path):
            return en_path
            
    return os.path.join(original_path, file_name)
